/* ==========================================================================
   RFM Bible Quiz — Question Bank
   40 questions. Each quiz session picks 10 at random.
   Difficulty mix: easy, medium, hard.
   ========================================================================== */
window.QUIZ_QUESTIONS = [
  // ---- OLD TESTAMENT ----
  { q: "Who built the ark that survived the great flood?",
    o: ["Moses", "Noah", "Abraham", "Elijah"], a: 1,
    e: "Noah built the ark by God's command and preserved his family and the animals through the flood. (Genesis 6–9)" },
  { q: "How many days and nights did Jonah spend inside the great fish?",
    o: ["Three", "Seven", "Twelve", "Forty"], a: 0,
    e: "Jonah was in the belly of the fish three days and three nights. (Jonah 1:17)" },
  { q: "Who led the Israelites out of Egypt?",
    o: ["Aaron", "Joshua", "Moses", "David"], a: 2,
    e: "Moses led the Israelites out of Egyptian slavery through the Red Sea and toward the Promised Land." },
  { q: "How many books are in the Old Testament?",
    o: ["27", "39", "50", "66"], a: 1,
    e: "The Protestant Old Testament contains 39 books. The whole Bible has 66." },
  { q: "Who was thrown into the lions' den for praying to God?",
    o: ["Elijah", "Daniel", "Elisha", "Jeremiah"], a: 1,
    e: "Daniel was thrown into the lions' den by King Darius, but God shut the lions' mouths. (Daniel 6)" },
  { q: "Which king wrote most of the Psalms?",
    o: ["Solomon", "Saul", "David", "Hezekiah"], a: 2,
    e: "King David wrote approximately 73 of the 150 Psalms." },
  { q: "Who was the wisest king of Israel?",
    o: ["David", "Solomon", "Josiah", "Rehoboam"], a: 1,
    e: "Solomon asked God for wisdom and received it in unmatched measure. (1 Kings 3)" },
  { q: "What did God create on the seventh day?",
    o: ["Man", "Light", "The animals", "Nothing — He rested"], a: 3,
    e: "On the seventh day God rested from all His work — establishing the Sabbath. (Genesis 2:2–3)" },
  { q: "Who was the strongest man in the Bible, whose strength came from his hair?",
    o: ["Goliath", "Samson", "Saul", "Gideon"], a: 1,
    e: "Samson's supernatural strength was tied to his Nazirite vow, symbolized by his uncut hair. (Judges 13–16)" },
  { q: "How many plagues did God send upon Egypt?",
    o: ["Seven", "Nine", "Ten", "Twelve"], a: 2,
    e: "Ten plagues, culminating in the death of the firstborn, led Pharaoh to release Israel. (Exodus 7–12)" },
  { q: "Who was the mother of Isaac?",
    o: ["Rebekah", "Sarah", "Rachel", "Leah"], a: 1,
    e: "Sarah gave birth to Isaac in her old age, fulfilling God's promise to Abraham. (Genesis 21)" },
  { q: "Which prophet was taken to heaven in a chariot of fire?",
    o: ["Elisha", "Isaiah", "Elijah", "Ezekiel"], a: 2,
    e: "Elijah was taken up to heaven in a whirlwind, with chariots and horses of fire. (2 Kings 2:11)" },
  { q: "How many days did God take to create the world?",
    o: ["Three", "Five", "Six", "Seven"], a: 2,
    e: "God created everything in six days and rested on the seventh. (Genesis 1)" },
  { q: "Who killed the giant Goliath?",
    o: ["Saul", "Jonathan", "David", "Samson"], a: 2,
    e: "The shepherd boy David defeated Goliath with a sling and stone, in the Lord's name. (1 Samuel 17)" },
  { q: "Which fruit did Adam and Eve eat that God forbade?",
    o: ["Apple", "Fig", "The Bible does not name the fruit", "Pomegranate"], a: 2,
    e: "Scripture only calls it 'the fruit of the tree of the knowledge of good and evil' — never an apple. (Genesis 3)" },

  // ---- NEW TESTAMENT / GOSPELS ----
  { q: "In which town was Jesus born?",
    o: ["Nazareth", "Jerusalem", "Bethlehem", "Capernaum"], a: 2,
    e: "Jesus was born in Bethlehem of Judea, fulfilling the prophecy of Micah 5:2. (Luke 2, Matthew 2)" },
  { q: "How many disciples did Jesus choose?",
    o: ["Seven", "Ten", "Twelve", "Seventy"], a: 2,
    e: "Jesus chose twelve apostles to be with Him and to send out. (Mark 3:14)" },
  { q: "Who baptized Jesus?",
    o: ["Peter", "John the Baptist", "Andrew", "Paul"], a: 1,
    e: "John the Baptist baptized Jesus in the Jordan River. (Matthew 3:13–17)" },
  { q: "What is the shortest verse in the Bible?",
    o: ["'God is love.'", "'Jesus wept.'", "'Rejoice always.'", "'Pray without ceasing.'"], a: 1,
    e: "'Jesus wept.' (John 11:35) — two words in English, spoken at Lazarus's tomb." },
  { q: "Who denied Jesus three times?",
    o: ["Judas", "Thomas", "Peter", "John"], a: 2,
    e: "Peter denied Jesus three times before the rooster crowed, as Jesus had foretold. (Luke 22:54–62)" },
  { q: "Which apostle was known for doubting the resurrection?",
    o: ["Andrew", "James", "Thomas", "Philip"], a: 2,
    e: "Thomas said he would not believe unless he touched Jesus's wounds — hence 'Doubting Thomas.' (John 20:24–29)" },
  { q: "How many books are in the New Testament?",
    o: ["27", "39", "50", "66"], a: 0,
    e: "The New Testament contains 27 books, from Matthew to Revelation." },
  { q: "On which day of the week did Jesus rise from the dead?",
    o: ["Friday", "Saturday", "Sunday", "Monday"], a: 2,
    e: "Jesus rose on the first day of the week — Sunday — the day now celebrated as the Lord's Day. (Matthew 28)" },
  { q: "How many loaves and fishes did Jesus use to feed the 5,000?",
    o: ["3 loaves, 2 fish", "5 loaves, 2 fish", "7 loaves, 3 fish", "12 loaves, 5 fish"], a: 1,
    e: "Jesus fed 5,000 men (plus women and children) with 5 loaves and 2 fish. (Matthew 14:13–21)" },
  { q: "Which apostle wrote the book of Revelation?",
    o: ["Peter", "Paul", "John", "James"], a: 2,
    e: "The apostle John received the vision on the island of Patmos and wrote Revelation. (Revelation 1)" },
  { q: "What is the first miracle Jesus performed?",
    o: ["Healing a leper", "Walking on water", "Turning water into wine", "Calming a storm"], a: 2,
    e: "Jesus turned water into wine at the wedding in Cana of Galilee. (John 2:1–11)" },
  { q: "Who was the Roman governor at Jesus's trial?",
    o: ["Herod", "Caesar", "Pontius Pilate", "Felix"], a: 2,
    e: "Pontius Pilate presided over Jesus's trial and reluctantly handed Him over to be crucified. (Matthew 27)" },
  { q: "How many days between Jesus's resurrection and ascension?",
    o: ["Seven", "Twenty", "Forty", "Fifty"], a: 2,
    e: "Jesus appeared to His disciples for 40 days after His resurrection before ascending. (Acts 1:3)" },
  { q: "What sign led the wise men to Jesus?",
    o: ["A dove", "A star", "An angel", "A rainbow"], a: 1,
    e: "The Magi followed a star that led them from the East to the child Jesus. (Matthew 2:1–12)" },
  { q: "Who was the father of John the Baptist?",
    o: ["Joseph", "Zacharias", "Simeon", "Elijah"], a: 1,
    e: "Zacharias (Zechariah), a priest, and his wife Elizabeth were the parents of John the Baptist. (Luke 1)" },

  // ---- EPISTLES / DOCTRINE ----
  { q: "'For God so loved the world…' — this famous verse is from which book?",
    o: ["John 3:16", "Romans 3:16", "1 John 3:16", "Matthew 3:16"], a: 0,
    e: "John 3:16 — perhaps the best-known verse in Scripture, summarizing the Gospel." },
  { q: "Which fruit of the Spirit comes first in Galatians 5:22?",
    o: ["Joy", "Love", "Peace", "Patience"], a: 1,
    e: "'The fruit of the Spirit is love, joy, peace, patience, kindness…' (Galatians 5:22)" },
  { q: "How many books are in the Bible in total?",
    o: ["55", "66", "72", "80"], a: 1,
    e: "The Protestant Bible has 66 books — 39 Old Testament and 27 New Testament." },
  { q: "Which apostle wrote the letter to the Romans?",
    o: ["Peter", "John", "Paul", "James"], a: 2,
    e: "The apostle Paul wrote the epistle to the Romans, his greatest doctrinal work." },
  { q: "'Faith without works is ____' — complete the verse.",
    o: ["cold", "dead", "empty", "weak"], a: 1,
    e: "'Faith without works is dead.' (James 2:26)" },
  { q: "What is the greatest commandment according to Jesus?",
    o: ["Do not steal", "Love God with all your heart", "Honor your parents", "Do not lie"], a: 1,
    e: "'You shall love the Lord your God with all your heart, soul, and mind.' (Matthew 22:37)" },
  { q: "Which two ordinances did Jesus command the Church to observe?",
    o: ["Fasting and tithing", "Baptism and the Lord's Supper", "Prayer and preaching", "Anointing and confession"], a: 1,
    e: "Jesus instituted baptism (Matthew 28) and the Lord's Supper (Luke 22) as ordinances for His Church." },
  { q: "How many chapters are in the book of Psalms?",
    o: ["100", "120", "150", "175"], a: 2,
    e: "The book of Psalms has 150 chapters — the longest book in the Bible." },
  { q: "Which is the longest book of the Bible by chapter count?",
    o: ["Genesis", "Isaiah", "Psalms", "Matthew"], a: 2,
    e: "Psalms has 150 chapters — more than any other book." },
  { q: "'The Lord is my shepherd; I shall not want.' From which Psalm?",
    o: ["Psalm 1", "Psalm 23", "Psalm 91", "Psalm 100"], a: 1,
    e: "Psalm 23 — perhaps the most beloved Psalm in Scripture." },
];
